const SHEET_NAME='Tasks';
const HEADERS=['ID','Task','Owner','Priority','Status','Progress','Latest Update','Manager Attention','Decision / Support Required','Archived','Created At','Updated At'];

function setupSheet(){const ss=SpreadsheetApp.getActiveSpreadsheet();let sh=ss.getSheetByName(SHEET_NAME)||ss.insertSheet(SHEET_NAME);sh.clear();sh.getRange(1,1,1,HEADERS.length).setValues([HEADERS]);formatSheet_(sh)}

// Run this once if upgrading from the original nine-column tracker.
function upgradeSheetToV2(){const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(SHEET_NAME);if(!sh)throw new Error('Tasks sheet not found');const current=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0];if(current.length===9&&current[0]==='ID'){sh.insertColumnsAfter(7,3);sh.getRange(1,1,1,HEADERS.length).setValues([HEADERS]);const last=sh.getLastRow();if(last>1)sh.getRange(2,8,last-1,3).setValues(Array.from({length:last-1},()=>[false,'',false]))}else if(current.join('|')!==HEADERS.join('|')){throw new Error('Unexpected columns. Back up the sheet, then align headers manually.')}formatSheet_(sh)}

function formatSheet_(sh){sh.setFrozenRows(1);sh.getRange(1,1,1,HEADERS.length).setFontWeight('bold').setBackground('#0f4c81').setFontColor('#ffffff');[170,260,120,100,140,90,460,130,360,90,155,155].forEach((w,i)=>sh.setColumnWidth(i+1,w));sh.getRange('D2:D').setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(['High','Medium','Low'],true).build());sh.getRange('E2:E').setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(['Not Started','In Progress','At Risk','Blocked','Near Completion','Completed'],true).build());sh.getRange('F2:F').setDataValidation(SpreadsheetApp.newDataValidation().requireNumberBetween(0,5).build()).setNumberFormat('0');sh.getRange('H2:H').insertCheckboxes();sh.getRange('J2:J').insertCheckboxes();sh.getRange('K2:L').setNumberFormat('yyyy-mm-dd hh:mm')}

function doGet(e){try{return json_({ok:true,tasks:listTasks_(String(e.parameter.archived)==='true')})}catch(err){return json_({ok:false,error:String(err.message||err)})}}
function doPost(e){const lock=LockService.getScriptLock();try{lock.waitLock(15000);const b=JSON.parse((e.postData&&e.postData.contents)||'{}');if(b.action==='create')return json_({ok:true,task:create_(b)});if(b.action==='update')return json_({ok:true,task:update_(b)});if(['archive','restore','delete'].includes(b.action))return json_({ok:true,result:lifecycle_(b.action,b.id)});return json_({ok:false,error:'Unknown action'})}catch(err){return json_({ok:false,error:String(err.message||err)})}finally{try{lock.releaseLock()}catch(_){}}}
function listTasks_(archived){const sh=getSheet_(),last=sh.getLastRow();if(last<2)return[];return sh.getRange(2,1,last-1,HEADERS.length).getValues().filter(r=>r[0]&&Boolean(r[9])===archived).map(rowToTask_)}
function create_(b){validate_(b);const now=new Date(),id=Utilities.getUuid();getSheet_().appendRow([id,b.task.trim(),b.owner.trim(),b.priority,b.status,Number(b.progress),b.update||'',Boolean(b.managerAttention),b.support||'',false,now,now]);return{id:id}}
function update_(b){validate_(b);const sh=getSheet_(),row=findRow_(sh,b.id),created=sh.getRange(row,11).getValue()||new Date(),archived=Boolean(sh.getRange(row,10).getValue());sh.getRange(row,1,1,HEADERS.length).setValues([[b.id,b.task.trim(),b.owner.trim(),b.priority,b.status,Number(b.progress),b.update||'',Boolean(b.managerAttention),b.support||'',archived,created,new Date()]]);return{id:b.id}}
function lifecycle_(action,id){const sh=getSheet_(),row=findRow_(sh,id);if(action==='delete'){if(!Boolean(sh.getRange(row,10).getValue()))throw new Error('Only archived tasks can be permanently deleted');sh.deleteRow(row);return'deleted'}sh.getRange(row,10).setValue(action==='archive');sh.getRange(row,12).setValue(new Date());return action==='archive'?'archived':'restored'}
function findRow_(sh,id){if(!id)throw new Error('Missing task ID');const last=sh.getLastRow();if(last<2)throw new Error('Task not found');const cell=sh.getRange(2,1,last-1,1).createTextFinder(id).matchEntireCell(true).findNext();if(!cell)throw new Error('Task not found');return cell.getRow()}
function validate_(b){const statuses=['Not Started','In Progress','At Risk','Blocked','Near Completion','Completed'],priorities=['High','Medium','Low'];if(!b.task||!b.owner)throw new Error('Task and owner are required');if(!priorities.includes(b.priority))throw new Error('Invalid priority');if(!statuses.includes(b.status))throw new Error('Invalid status');const p=Number(b.progress);if(!Number.isInteger(p)||p<0||p>5)throw new Error('Progress must be an integer from 0 to 5')}
function rowToTask_(r){return{id:String(r[0]),task:String(r[1]||''),owner:String(r[2]||''),priority:String(r[3]||''),status:String(r[4]||''),progress:Number(r[5]||0),update:String(r[6]||''),managerAttention:Boolean(r[7]),support:String(r[8]||''),archived:Boolean(r[9]),createdAt:date_(r[10]),updatedAt:date_(r[11])}}
function date_(v){return v instanceof Date?v.toISOString():String(v||'')}
function getSheet_(){const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(SHEET_NAME);if(!sh)throw new Error('Run setupSheet() once first');return sh}
function json_(d){return ContentService.createTextOutput(JSON.stringify(d)).setMimeType(ContentService.MimeType.JSON)}